apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dragonfly
  namespace: dragonfly
  labels:
    app.kubernetes.io/name: dragonfly
spec:
  replicas: 1
  serviceName: dragonfly
  selector:
    matchLabels:
      app.kubernetes.io/name: dragonfly
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dragonfly
    spec:
      containers:
        - name: dragonfly
          image: docker.dragonflydb.io/dragonflydb/dragonfly
          ports:
          - name: internal
            containerPort: 6379
            protocol: TCP
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: dragonfly-data
              mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: dragonfly-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: dragonfly
  namespace: dragonfly
spec:
  selector:
    app.kubernetes.io/name: dragonfly
  ports:
    - protocol: TCP
      port: 6379
      targetPort: internal
  type: LoadBalancer
