apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: kafka
  name: kafka
  labels:
    app.kubernetes.io/name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka
  serviceName: kafka
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: kafka
        image: "apache/kafka:3.8.0"
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
        ports:
        - name: internal
          containerPort: 9092
          protocol: TCP
        - name: external
          containerPort: 9094
          protocol: TCP
        env:
        - name: KAFKA_HEAP_OPTS
          value : "-Xmx512M -Xms512M"
        - name: KAFKA_OPTS
          value: "-Dlogging.level=INFO"
        - name: KAFKA_NODE_ID
          value: "1"
        - name: KAFKA_PROCESS_ROLES
          value: broker,controller
        - name: KAFKA_LISTENERS
          value: INTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094
        - name: KAFKA_ADVERTISED_LISTENERS
          value: INTERNAL://kafka.kafka:9092,EXTERNAL://10.96.11.51:9094
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: CONTROLLER
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INTERNAL
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: 1@localhost:9093
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
      volumes:
      - name: kafka-data
        persistentVolumeClaim:
          claimName: kafka-data
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
  labels:
    app.kubernetes.io/name: kafka
  annotations:
    networking.gke.io/load-balancer-type: Internal
spec:
  clusterIP: 10.96.11.51
  selector:
    app.kubernetes.io/name: kafka
  ports:
  - name: internal
    port: 9092
    targetPort: plaintext
  - name: external
    port: 9094
    targetPort: external
  type: LoadBalancer
